/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confirm API availability and deployment health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start passwordless sign-in by emailing a one-time magic link */
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a one-time magic-link token and establish a session */
        post: operations["verifyMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve the authenticated user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active food categories for form dropdowns and validation */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List locations according to the authenticated user's role
         * @description HUB users receive only their own assigned location, never the full list. ADMIN may include inactive locations via `active=false`.
         */
        get: operations["listLocations"];
        put?: never;
        /** Create a new hub or food centre */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a location name, type, or active status */
        patch: operations["updateLocation"];
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List and filter weigh entries permitted for the authenticated user
         * @description HUB role is restricted to entries where location_id equals the user's assigned location; any other requested location_id is ignored or rejected server-side, never trusted from the client.
         */
        get: operations["listEntries"];
        put?: never;
        /**
         * Create a single weigh-in or weigh-out entry
         * @description Role rules enforced server-side: HUB may only create IN entries at their own assigned location with destination_location_id null; FOOD_CENTRE may create IN at the centre or OUT to any hub; ADMIN may create either for any valid location.
         */
        post: operations["createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync offline entries from the PWA in an idempotent way
         * @description Uses client_uuid to deduplicate. An entry with a client_uuid that already exists is returned as status "duplicate", not an error -- this is the offline-sync-safe behaviour the PWA's queue relies on.
         */
        post: operations["bulkSyncEntries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve one specific entry if permitted by role and location access */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct an existing entry */
        patch: operations["correctEntry"];
        trace?: never;
    };
    "/entries/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Void an incorrect entry without hard-deleting it */
        post: operations["voidEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve Monday-to-Sunday weekly totals by location and category
         * @description HUB may only view their own hub's report; any other requested location_id is ignored or rejected server-side. week_start must be a Monday or the API returns a validation error.
         */
        get: operations["getWeeklyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/weekly/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the Monday-to-Sunday weekly report matching the current spreadsheet layout
         * @description V1 restricts this to ADMIN. Exact column layout is PENDING operational validation against the real CSF spreadsheet template -- see Step 3/4 notes.
         */
        get: operations["exportWeeklyCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users for administration */
        get: operations["listUsers"];
        put?: never;
        /** Create a new user account without a password */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user name, email, role, location, or active status */
        patch: operations["updateUser"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "ADMIN" | "FOOD_CENTRE" | "HUB";
        /** @enum {string} */
        EntryType: "IN" | "OUT";
        /** @enum {string} */
        EntryStatus: "ACTIVE" | "VOID";
        /** @enum {string} */
        LocationType: "HUB" | "FOOD_CENTRE";
        /** @enum {string} */
        FoodCategoryCode: "FRESH" | "FROZEN" | "AMBIENT";
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            location_id?: string | null;
            active: boolean;
            /** Format: date-time */
            last_login_at?: string | null;
        };
        Location: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["LocationType"];
            active: boolean;
        };
        FoodCategory: {
            code: components["schemas"]["FoodCategoryCode"];
            name: string;
            active: boolean;
        };
        Entry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            client_uuid?: string | null;
            entry_type: components["schemas"]["EntryType"];
            /** Format: uuid */
            location_id: string;
            /** Format: uuid */
            destination_location_id?: string | null;
            food_category_code: components["schemas"]["FoodCategoryCode"];
            weight_kg: number;
            /** Format: date */
            collection_date: string;
            notes?: string | null;
            status: components["schemas"]["EntryStatus"];
            void_reason?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            updated_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Pagination: {
            page: number;
            limit: number;
            total: number;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
            };
        };
        CategoryTotals: {
            FRESH?: number;
            FROZEN?: number;
            AMBIENT?: number;
        };
        WeeklyReport: {
            /** Format: date */
            week_start: string;
            /** Format: date */
            week_end: string;
            totals: {
                in_by_category: components["schemas"]["CategoryTotals"];
                out_by_category: components["schemas"]["CategoryTotals"];
            };
            by_location: {
                /** Format: uuid */
                location_id: string;
                location_name: string;
                in_by_category: components["schemas"]["CategoryTotals"];
                out_by_category: components["schemas"]["CategoryTotals"];
            }[];
        };
    };
    responses: {
        /** @description Input failed validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated but not permitted for this role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        version: string;
                    };
                };
            };
        };
    };
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Always a generic success, whether or not the email exists or is active, to avoid user enumeration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "requested";
                    };
                };
            };
        };
    };
    verifyMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Sets the httpOnly session cookie via Set-Cookie. Response body does not include the token itself. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            /** @description Token expired, already used, or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodCategory"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLocations: {
        parameters: {
            query?: {
                active?: boolean;
                type?: components["schemas"]["LocationType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    type: components["schemas"]["LocationType"];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    type?: components["schemas"]["LocationType"];
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEntries: {
        parameters: {
            query?: {
                week_start?: string;
                from?: string;
                to?: string;
                location_id?: string;
                destination_location_id?: string;
                entry_type?: components["schemas"]["EntryType"];
                food_category_code?: components["schemas"]["FoodCategoryCode"];
                status?: components["schemas"]["EntryStatus"];
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: components["schemas"]["Entry"][];
                        pagination: components["schemas"]["Pagination"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    client_uuid: string;
                    entry_type: components["schemas"]["EntryType"];
                    /** Format: uuid */
                    location_id: string;
                    /** Format: uuid */
                    destination_location_id?: string | null;
                    food_category_code: components["schemas"]["FoodCategoryCode"];
                    weight_kg: number;
                    /** Format: date */
                    collection_date: string;
                    notes?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entry: components["schemas"]["Entry"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    bulkSyncEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entries: {
                        /** Format: uuid */
                        client_uuid: string;
                        entry_type: components["schemas"]["EntryType"];
                        /** Format: uuid */
                        location_id: string;
                        /** Format: uuid */
                        destination_location_id?: string | null;
                        food_category_code: components["schemas"]["FoodCategoryCode"];
                        weight_kg: number;
                        /** Format: date */
                        collection_date: string;
                        notes?: string | null;
                    }[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: {
                            /** Format: uuid */
                            client_uuid: string;
                            /** @enum {string} */
                            status: "created" | "duplicate" | "error";
                            /** Format: uuid */
                            id?: string | null;
                            message?: string | null;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entry: components["schemas"]["Entry"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    correctEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    location_id?: string;
                    /** Format: uuid */
                    destination_location_id?: string | null;
                    food_category_code?: components["schemas"]["FoodCategoryCode"];
                    weight_kg?: number;
                    /** Format: date */
                    collection_date?: string;
                    notes?: string | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entry: components["schemas"]["Entry"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    voidEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entry: components["schemas"]["Entry"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getWeeklyReport: {
        parameters: {
            query: {
                week_start: string;
                location_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description week_start is not a Monday */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    exportWeeklyCsv: {
        parameters: {
            query: {
                week_start: string;
                location_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                active?: boolean;
                role?: components["schemas"]["Role"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email: string;
                    role: components["schemas"]["Role"];
                    /** Format: uuid */
                    location_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: email */
                    email?: string;
                    role?: components["schemas"]["Role"];
                    /** Format: uuid */
                    location_id?: string | null;
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
